name: "set custom env variable"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DAY: "Friday"

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MONTH: "September"
    steps:
        - name: Check out repository
          uses: actions/checkout@v4 
        - name: find value
          run : |
            echo "The value of DAY is $DAY"
            echo "The value of MONTH is $MONTH"
            echo "The value of YEAR is $YEAR"
          env:
            YEAR: "2025"