name: multi event

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: setup java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: code compilation
      run: mvn compile
    - name: codereview
      run: mvn -P metrics pmd:pmd
    - name: unittest
      run: mvn test
    - name: package
      run: mvn package
      
