name: "set secrets variables"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4   

      - name: set secrets repo level
        run: |
          echo "the username is "${{ secrets.MY_SECRET.uname }}""
          echo "the password is "${{ secrets.MY_SECRET.pass }}""
        
        