name: Use Repo Secret

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write secret to file
        run: |
          echo "${{ secrets.MY_SECRET }}" > a.txt
          cat a.txt   # just to verify, in real use don’t log secrets

      - name: Parse username and password
        run: |
          UNAME=$(grep 'uname' a.txt | awk -F": " '{print $2}' | tr -d "'\"")
          PASS=$(grep 'pass' a.txt | awk -F": " '{print $2}' | tr -d "'\"")

          echo "Username: $UNAME"
          echo "Password: $PASS"
