name: "workflow-commands"

on:
  push: 
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: find value
        run: |
          echo "$GITHUB_ENV"
          echo "$GITHUB_PATH"
          echo "$GITHUB_WORKSPACE"
          echo "$GITHUB_EVENT_PATH"
          echo "$GITHUB_JOB"
          echo "$GITHUB_RUN_ID"